// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDiWfOQDeQ3ZKD1cCGPi1L_BI8B23k_RkU',
    appId: '1:831060358644:web:044c884ca6a12e3592b5a1',
    messagingSenderId: '831060358644',
    projectId: 'urbanna-515b0',
    authDomain: 'urbanna-515b0.firebaseapp.com',
    databaseURL: 'https://urbanna-515b0-default-rtdb.firebaseio.com',
    storageBucket: 'urbanna-515b0.firebasestorage.app',
    measurementId: 'G-1BFMTFYGEW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD1aC0kJ8cZZz0ix0xyHg2Uiv-mf8SuGYc',
    appId: '1:831060358644:android:66097ab27678dac392b5a1',
    messagingSenderId: '831060358644',
    projectId: 'urbanna-515b0',
    databaseURL: 'https://urbanna-515b0-default-rtdb.firebaseio.com',
    storageBucket: 'urbanna-515b0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyByE1otHWzEZvpMNyf4WjQbdd9j1fmQJb8',
    appId: '1:831060358644:ios:3b613b0287f75a9c92b5a1',
    messagingSenderId: '831060358644',
    projectId: 'urbanna-515b0',
    databaseURL: 'https://urbanna-515b0-default-rtdb.firebaseio.com',
    storageBucket: 'urbanna-515b0.firebasestorage.app',
    iosBundleId: 'com.example.urbanna',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyByE1otHWzEZvpMNyf4WjQbdd9j1fmQJb8',
    appId: '1:831060358644:ios:3b613b0287f75a9c92b5a1',
    messagingSenderId: '831060358644',
    projectId: 'urbanna-515b0',
    databaseURL: 'https://urbanna-515b0-default-rtdb.firebaseio.com',
    storageBucket: 'urbanna-515b0.firebasestorage.app',
    iosBundleId: 'com.example.urbanna',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDiWfOQDeQ3ZKD1cCGPi1L_BI8B23k_RkU',
    appId: '1:831060358644:web:80b439be9af79da292b5a1',
    messagingSenderId: '831060358644',
    projectId: 'urbanna-515b0',
    authDomain: 'urbanna-515b0.firebaseapp.com',
    databaseURL: 'https://urbanna-515b0-default-rtdb.firebaseio.com',
    storageBucket: 'urbanna-515b0.firebasestorage.app',
    measurementId: 'G-NRJY3V5N4Y',
  );
}
